webb/IO/urls.py
from django.urls import path
from .views import *
from history.views import *
from UTIL.config import AGREE

## UTIL/config.py 파일의 AGREE 변수에 맞춰 표시되는 페이지 수정  ##
BOARD = 'board/' if AGREE else ''
AGREE_PAGE = '' if AGREE  else 'agree/'

urlpatterns = [
    path(BOARD, board, name='board'),
    path(AGREE_PAGE, agree, name='agree'),
    path('agreeimgsave/', agreeimgsave, name='agreeimgsave'),
    path('edit/<int:pk>', boardEdit, name='edit'),
    path('delete/<int:pk>', boardDelete, name='delete'),
    path('<int:id>', tagging_history_detail, name='detail'),
]

webb/chart/urls.py
from django.urls import path
from .views import *

app_name = 'chart' 
urlpatterns = [
    path('', chart_page, name='chart_page'),
]

webb/history/urls.py
from django.urls import path
from .views import *

app_name = 'history' 
urlpatterns = [
    path('', tagging_history_total_list, name='tagging_patient_total_history'),
    path('tagging_history', tagging_history_partial_list, name='tagging_history'),
    path('pretagging',tagging_tables_pre_tagging, name = 'tagging_tables_pre_tagging'),
    path('preinterpretation', tagging_tables_pre_interpretion, name = 'tagging_tables_pre_interpretion'),

    path('<int:id>', tagging_history_detail, name='detail'),

    path('remove/<int:pk>', HDDelete, name='remove'),
    path('<int:id>/ments', tagging_history_detail, name='detail2'),
    path('<int:id>/ments/<int:comment_id>', ment_delete, name='ment_delete'),




    path('like', like ,name='like'), path('like_ready', like_ready,name='like_ready'),
    path('dislike', dislike ,name='dislike'), path('dislike_ready', dislike_ready,name='dislike_ready'),
    path('tagging_reset_like', tagging_reset_like ,name='tagging_reset_like'), path('tagging_reset_dislike', tagging_reset_dislike ,name='tagging_reset_dislike'),
    
    path('like1', like1 ,name='like1'), path('like_ready1', like_ready1,name='like_ready1'),
    path('dislike1', dislike1 ,name='dislike1'), path('dislike_ready1', dislike_ready1,name='dislike_ready1'),
    path('tagging_reset_like1', tagging_reset_like1 ,name='tagging_reset_like1'), path('tagging_reset_dislike1', tagging_reset_dislike1 ,name='tagging_reset_dislike1'),

    path('like2', like2 ,name='like2'), path('like_ready2', like_ready2,name='like_ready2'),
    path('dislike2', dislike2 ,name='dislike2'), path('dislike_ready2', dislike_ready2,name='dislike_ready2'),
    path('tagging_reset_like2', tagging_reset_like2 ,name='tagging_reset_like2'), path('tagging_reset_dislike2', tagging_reset_dislike2 ,name='tagging_reset_dislike2'),

    path('like3', like3 ,name='like3'), path('like_ready3', like_ready3,name='like_ready3'),
    path('dislike3', dislike3 ,name='dislike3'), path('dislike_ready3', dislike_ready3,name='dislike_ready3'),
    path('tagging_reset_like3', tagging_reset_like3 ,name='tagging_reset_like3'), path('tagging_reset_dislike3', tagging_reset_dislike3 ,name='tagging_reset_dislike3'),
]

webb/lt4/urls.py
from django.views.generic import TemplateView
from django.contrib import admin
from django.urls import path, re_path
from django.urls.conf import include
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    #path(r'', include('service.urls')),
    path('grappelli/', include('grappelli.urls')), # grappelli URLS
    path('admin/', admin.site.urls),
    path('',include('IO.urls')),
    path('accounts/',include('accounts.urls')),
    path('history/',include('history.urls', namespace=' src')),
    path('chart/', include('chart.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),

    ## 테스트용 url
                
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webb/main/lt4/urls.py
from django.views.generic import TemplateView
from django.contrib import admin
from django.urls import path, re_path
from django.urls.conf import include
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('IO.urls')),
    path('accounts/',include('accounts.urls')),
    path('history/',include('history.urls', namespace=' src')),
    path('chart/', include('chart.urls')),
    path('tagging/',include('tagging.urls')),


                
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webb/chart/models.py
from django.db import models

# Create your models here.

webb/chart/views.py
from django.views.decorators.csrf import csrf_exempt
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from history.models import PatientDB
from chart.templatetags import utils
from UTIL import config

@csrf_exempt
def chart_page(request):
    ## PatientDB에서 현재 로그인 되어 있는 id로 게시된 게시물 목록을 가져옴. ##
    ## user_id : 현재 로그인 되어 있는 id 정보 ##
    ## partial_db: 현재 로그인 되어 있는 id로  등록 되어있는 레코드 목록 ##

    ## 로그인 되어있으면 history 페이지로 이동 ##
    if request.user.is_authenticated:
        user_id = request.user
        partial_db = PatientDB.objects.filter(user_id = user_id)
        total_db = PatientDB.objects.order_by('-visit_date')

        ## user_idx : 게시글 목록에서 첫 번째 게시글의 User id 인덱스 값을 가지고 옴. ##
        ## user_name : 가입된 계정들 DB에서의 user_idx값을 조회하여 user_name을 가지고 옴. ##
        try:
            user_idx = partial_db[0].user_id
            user_name = User.objects.filter(id = user_idx)
            user_name = user_name[0].username

        except:
            ## media/log 폴더에 로그 작성해주는 코드 자세한 코드는 UTIL/config.py 참조
            config.log_writer(f'DB에서 사용자 id를 가져올 수 없어 현재 로그인 되어있는 id를 사용합니다.', level='warn')
            user_name = user_id

        ## total_chart_dict : 전체 계정의 환자 통계 자료를 저장시켜주는 변수 ##
        total_chart_dict =  {
            'K-TIRADS' : {k : 0 for  k in ['C1', 'C2', 'C3', 'C4', 'C5']},
            'Malignant' : {m : 0 for m in ['Absent', 'Benign', 'Malignant']},
            'Positive' : {p :0 for p in ['Absent', 'Negative', 'Positive']}
        }


        ## partial_chart_dict : 로그인 되어 있는 계정의 환자 통계 자료를 저장시켜주는 변수 ##
        partial_chart_dict =  {
            user_name : {
            'K-TIRADS' : {k : 0 for  k in ['C1', 'C2', 'C3', 'C4', 'C5']},
            'Malignant' : {m : 0 for m in ['Absent', 'Benign', 'Malignant']},
            'Positive' : {p :0 for p in ['Absent', 'Negative', 'Positive']}
            }
        }

        ##  DB에 있는 json 경로들을 이용해 K-TIRADS, Malignant/Benign .... 등 수치를 가져오도록 함. ##
        ##  수치를 가져오는 자세한 코드는 /home/super/바탕화면/share/lt4/chart/templatetags/utils.py 참조 ##
        for data in total_db: total_chart_data = utils.total_chart_data(total_chart_dict, data.json_path)
        for data in partial_db: partial_chart_data = utils.partial_chart_data(partial_chart_dict, user_name, data.json_path)[user_name]

        ## 파이차트에 적어줄 범례(legend)들 ##
        k_labels, m_labels, p_labels = [f'C{idx}' for idx in range(1, 6)], [ 'Absent', 'Benign', 'Malignant'], [ 'Absent', 'Negative', 'Positive']
        
        
        ## 환자 이력 DB에 데이터가 있을 경우에 k_datas, m_datas, p_datas를 가져옴. ##
        ## tk_datas (total k-tirads datas) : 전체 사용자의 k-tirads 데이터만 담겨져 있는 데이터
        ## tm_datas (total malignant datas) : 전체 사용자의 malignant 데이터만 담겨져 있는 데이터
        ## tp_datas (total positive datas) : 전체 사용자의 positive 데이터만 담겨져 있는 데이터
        try:
            tk_datas = [tkv for tkv in total_chart_data['K-TIRADS'].values()]
            tm_datas = [tmv for tmv in total_chart_data['Malignant'].values()]
            tp_datas = [tpv for tpv in total_chart_data['Positive'].values()]
            
        except Exception as e:
            ## media/log 폴더에 로그 작성해주는 코드 자세한 코드는 UTIL/config.py 참조
            config.log_writer('전체 검진 데이터가 존재하지 않습니다. - {e}', level='err')
            print('[ERROR] 전체 데이터가 존재하질 않습니다.')
            tk_datas, tm_datas, tp_datas = [0, 0, 0, 0], [0, 0], [0, 0]

        ## 환자 이력 DB에 데이터가 있을 경우에 k_datas, m_datas, p_datas를 가져옴. ##
        ## pk_datas (partial k-tirads datas) : 현재 로그인 되어있는 사용자의 k-tirads 데이터만 담겨져 있는 데이터
        ## pm_datas (partial malignant datas) : 현재 로그인 되어있는 사용자의 malignant 데이터만 담겨져 있는 데이터
        ## pp_datas (partial positive datas) : 현재 로그인 되어있는 사용자의 positive 데이터만 담겨져 있는 데이터
        try:
            pk_datas = [pkv for pkv in partial_chart_data['K-TIRADS'].values()]
            pm_datas = [pmv for pmv in partial_chart_data['Malignant'].values()]
            pp_datas = [ppv for ppv in partial_chart_data['Positive'].values()]

        except Exception as e:
            ## media/log 폴더에 로그 작성해주는 코드 자세한 코드는 UTIL/config.py 참조
            config.log_writer(f'{user_name}님의 검진 데이터가 존재하지 않습니다. - {e}', level='err')
            print(f'[ERROR] {user_name}님의 데이터가 존재하질 않습니다.')
            pk_datas, pm_datas, pp_datas = [0, 0, 0, 0], [0, 0], [0, 0]

        context = {'user_name' : user_name, 'total_db' : total_db, 'partial_db' : partial_db, 
                        'tk_datas' : tk_datas, 'pk_datas' : pk_datas, 'k_labels' : k_labels,
                        'tm_datas' : tm_datas, 'pm_datas' : pm_datas, 'm_labels' : m_labels , 
                        'tp_datas' : tp_datas, 'pp_datas' : pp_datas, 'p_labels' : p_labels}

        return render(request, 'charts.html', context)

        ## 로그인 되어 있지 않으면 로그인 페이지로 이동 후 검사 페이지로 이동 ##
    else:
        return redirect('login')

webb/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
    <head>
        {% include 'head.html' %}
        <!-- 이미지 우클릭 했을때 다운 받지 못하도록 하는 함수 -->
        <script type="text/javascript">
            document.oncontextmenu = function(){return false;}
        </script>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <!-- Our Custom CSS -->
        <link rel="stylesheet" type="text/css" href="{% static 'css/sidebar_style.css' %}">
       
        
        <!-- div class = "a" 시에 확대 history_blank의 결절 부분에만 적용-->  
        <style>
            .a {
                width: 400px;
                margin: 0px auto;
            }
            .a:hover img {
                transform: scale(2.0);
            }

            
            .modal{ 
                position:absolute; width:100%; height:100%; background: rgba(0,0,0,0.8); top:0; left:0; display:none;
            }

            #drop-area {
            border: 4px dashed skyblue;
            border-radius: 20px;
            width: 100%;
            font-family: sans-serif;
            margin: 20px auto;
            padding: 20px;
            }

            #drop-area.highlight {
            border-color: purple;
            }

            /* p {
            margin-top: 0;
            text-align: center;
            font-size: 2em;
            font-family: 'Playfair Display', serif;
            } */

            .my-form {
            margin-bottom: 10px;
            }

            #gallery {
            margin-top: 10px;
            }

            #gallery img {
            width: auto;
            height: 150px;
            margin-bottom: 10px;
            margin-right: 10px;
            vertical-align: middle;
            object-fit: cover;

            }

            .button {
            display: inline-block;
            padding: 10px;
            margin: 0 22%;
            background: skyblue;
            cursor: pointer;
            border-radius: 5px;
            border: 1px solid skyblue;
            font-family: 'Roboto', serif;
            }

            .button:hover {
            background: skyblue;
            color: #ffffff;
            font-weight: bold;
            }

            #fileElem {
            display: none;
            }

            progress[value] {
            /* Reset the default appearance */
            -webkit-appearance: none;
            appearance: none;
            width: 100%;
            height: 15px;
            }

            progress[value]::-webkit-progress-bar {
            background-color: #eee;
            border-radius: 2px;
            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.25) inset;
            }

            progress[value]::-webkit-progress-value {
            background-image: -webkit-linear-gradient(-45deg, transparent 33%, rgba(0, 0, 0, .1) 33%, rgba(0, 0, 0, .1) 66%, transparent 66%), -webkit-linear-gradient(top, rgba(255, 255, 255, .25), rgba(0, 0, 0, .25)), -webkit-linear-gradient(left, #09c, #f44);
            border-radius: 2px;
            background-size: 35px 20px, 100% 100%, 100% 100%;
            }
        </style>
    </head>
    <body oncontextmenu="return false" onselectstart="return false" ondragstart="return false">
        <!-- onselectstart : 마우스 드래그 방지 -->
        <!-- ondragstart : 이미지 복사드래그 방지 -->
        <!-- onkeydown : 키보드 단축키 복사 방지 -->
        {% include 'body.html' %}
        {% block content %}
        {% endblock %}

        <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
        <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    </body>
</html>

webb/templates/body.html
{% load static %}

<!-- Page Wrapper -->
<div id="wrapper">

    <!-- Sidebar -->
    <ul class="navbar-nav bg-gradient-secondary sidebar sidebar-dark accordion" id="sidebar">

        <!-- Sidebar - Brand -->
        <a class="sidebar-brand d-flex align-items-center justify-content-center">
            <div class="sidebar-brand-icon rotate-n-0">
                <img id = "logo" style="width: 200px;" src="{% static 'img/ltlux-logo.png' %}"></img>
            </div>
        </a>

        <!-- Divider -->
        <hr class="sidebar-divider my-0">
        <hr class="sidebar-divider">

        <li class="nav-item active">
            
            <div id="collapsePages" class="collapse show" aria-labelledby="headingPages" data-parent="#accordionSidebar">
                <div class="bg-white py-2 collapse-inner rounded">
                    <h6 class="collapse-header">Interpretation Pages:</h6>
                    {% if True %}
                        <a class="collapse-item" href="{% url 'board' %}">AI Interpretation</a>
                    {% else %}
                        <a class="collapse-item" href="{% url 'agree' %}">AI Interpretation</a>
                    {% endif %}
                    <h6 class="collapse-header">Clinic Pages:</h6>
                    <a class="collapse-item" href="{% url 'history:tagging_patient_total_history' %}">Tagging </a>
                    <a class="collapse-item" href="{% url 'history:tagging_tables_pre_interpretion' %}">Pre - Interpretation </a>
                    <a class="collapse-item" href="{% url 'history:tagging_tables_pre_tagging' %}">Pre - Tagging</a>
                    <a class="collapse-item" href="{% url 'history:tagging_history' %}">Tagging history</a>
                    <h6 class="collapse-header">AI quantitative measuring:</h6>
                    <a class="collapse-item" href="{% url 'chart:chart_page' %}">Chart</a> 
                    <h6 class="collapse-header">Login Screens:</h6>
                    <a class="collapse-item" href="{% url 'logout' %}">Logout</a>
                </div>
            </div>
        </li>
    </ul>

webb/templates/head.html
{% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>LTLUX beta</title>
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/logo.png' %}">

    <!-- Custom fonts for this template-->
    <link rel="stylesheet" href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" type="text/css">

    <!-- Custom styles for this template-->
    <link rel="stylesheet" href="{% static 'css/sb-admin-2.min.css' %}" >

    <!--    CSS    -->
    <link rel="stylesheet" href="{% static 'css/default.css' %}" >

    <!-- Custom fonts for this template-->
    <link rel="stylesheet" href="{% static 'vendor/fontawesome-free/css/all.min.css' %}"  type="text/css">

    <!-- Custom styles for this template-->
    <link rel="stylesheet" href="{% static 'css/sb-admin-2.min.css' %}" >
    
    <!--    BOOTSTRAP4 CDN-->
    <script src = '{% static "js/jquery-3.3.1.slim.min.js" %}'></script>
    
    

webb/templates/header.html
<!-- <div >
    <ul > 로그인된상태에서만 대시보드 접근가능하도록 
        {% if user.is_authenticated %}
            <div class="logout_div" >
                <ul class="underline-hover">
                    <li class="logout_text"><a href="{% url 'board' %}"><span>홈</span></a></li>
                    <li class="logout_text"><a href="{% url 'board' %}"><span>게시판</span></a></li>
                    <li class="logout_text"><a href="{% url 'logout' %}"><span>로그아웃</span></a></li>
                </ul>
            </div>
        {% else %}
            <div class="login_div">
                <ul class="underline-hover">
                    <li class="login_text"><a href="{% url 'login' %}"><span>로그인</span></a></li>
                    <li class="login_text"><a href="{% url 'signup' %}"><span>회원가입</span></a></li>
                </ul>
            </div>
        {% endif %}
    </ul>
</div> -->

webb/templates/home.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
<div>
    <h3><a href="signup">회원가입</a></h3>
    <h3><a href="login">로그인</a></h3>
    <h3><a href="logout">로그아웃</a></h3>
</div>
{% endblock %}

webb/templates/login.html
{% extends 'login_base.html' %}
{% load bootstrap4 %}
{% load static %}
{% block content %}
    <div id = 'wrapper'>
        <div class="container">
            <!-- Outer Row -->
            <div class="row justify-content-center">
                <div class="card o-hidden border-0 shadow-lg my-5">
                    <div class="card-body p-0" style="min-width: 463.27px;">
                        <!-- Nested Row within Card Body -->
                        <div class="p-5">
                            <div class="text-center">
                                <a class="sidebar-brand d-flex align-items-center justify-content-center">
                                    <div class="logo_img">
                                        <img style="width: 250px;  display: block; margin: 0 auto;" src="{% static 'img/ltlux-logo.png' %}"></img>
                                    </div>
                                </a>
                            </div>
                           
                            <form method="POST" >
                                {% csrf_token %}
                                <input  name="username" type="text" class="form-control form-control-user" placeholder="아이디" required>
                                <input name="password" type="password" class="form-control form-control-user" placeholder="비밀번호" required>
                                <div class="custom-control custom-checkbox small">
                                    <input type="checkbox" class="custom-control-input" id="customCheck">
                                    <label class="custom-control-label" for="customCheck">로그인 상태 유지</label>
                                    <input type="submit" id="login-submit" class="btn btn-primary btn-user btn-block" value="로그인">
                                </div>
                            
                                <!-- 로그인 오류 메세지 창 띄우는 곳-->
                          
                                {% if messages %}
                                <ul class="messages" id = "warning_login">
                                    {% for message in messages %}
                                    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                                    {% endfor %}
                                </ul>
                                {% endif %}
                 
            
                            <br>
                            </form>
                            <hr id = "login_hr">
                            <div class="text-center">
                                <li class="login_text">
                                    <a href="{% url 'signup' %}">
                                        <span>회원가입</span>
                                    </a>
                                </li>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>    
    </div>
{% endblock %}

webb/templates/login_base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
    <head>
        {% include 'login_head.html' %}
    </head>
    
    <body class="bg-gradient-primary">
        {% block content %}
        {% endblock %}
    </body>

    <footer>
        <div>
            <hr>
            <img class = "footer_img" src="{% static 'img/lt4_logo.png' %}"></img>
                Copyright © Lt4 Corp. All Rights Reserved.
        </div>    
    </footer>
</html>

webb/templates/login_head.html
{% load static %}
    <meta charset="UTF-8">
    <title>LTLUX beta</title>
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/logo.png' %}">

    <!--    CSS    -->
    <link rel="stylesheet" href="{% static 'css/default.css' %}">

    {% block js%}
    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static 'js/sb-admin-2.min.js' %}"></script>
    {% endblock js %}

webb/templates/signup.html
<!DOCTYPE html>
<html lang="en">
{% extends 'login_base.html' %}
{% load bootstrap4 %}
{% block content %}
{% load static %}



<div id = 'wrapper2'>
    <div class="container">
        <div class="card o-hidden border-0 shadow-lg my-5">
            <div class="card-body p-0">
                <!-- Nested Row within Card Body -->
                <div class="row">
                    <div class="col-lg-7">
                        <div class="p-5">
                            <div class="account">
                                <h1 class="h4 text-gray-900 mb-4">회원가입</h1>
                            </div>
                                <form method="POST">
                                    {% csrf_token %}
                                    <div class="form-group row">
                                        <div class="col-sm-6 mb-3 mb-sm-0">
                                            <input name="username" type="text" class="form-control form-control-user"  placeholder="아이디" required>
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <div class="col-sm-6 mb-3 mb-sm-0">
                                            <input name="password1" type="password" class="form-control form-control-user" placeholder="비밀번호" required>
                                        </div>
                                    </div>
                                    <div class="form-group row"> 
                                        <div class="col-sm-6 mb-3 mb-sm-0">  
                                            <input name="password2" type="password" class="form-control form-control-user" placeholder="비밀번호 재확인"  required>
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <div class="col-sm-6 mb-3 mb-sm-0">
                                            <input name="Name" type="text" placeholder="이름" required>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <input name="email" type="email" class="form-control form-control-user"
                                            placeholder="이메일" required>
                                    </div>
                                    <div class="form-group">
                                        <input name="phonenumber" type="tel" class="form-control form-control-user"
                                            placeholder="휴대폰번호" required>
                                    </div>
                                    <div class="form-group row">
                                        <div class="col-sm-6 mb-3 mb-sm-0">
                                            <input name="License Number" type="text" placeholder="의사면허번호" required>
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <div class="col-sm-6 mb-3 mb-sm-0">
                                            <input name="Affiliation" type="text" placeholder="소속" required>
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <div class="col-sm-6 mb-3 mb-sm-0">
                                            <input name="Rank" type="text" placeholder="직급 / 직위" required>
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <div class="col-sm-6 mb-3 mb-sm-0">
                                            <input name="Subject" type="text" placeholder="진료 과목" required>
                                        </div>
                                    </div>
                                    <input a href="{% url 'login' %}" type="submit" class="create_btn" value="계정생성 ">
                                    <button class = "home_button" type = "button" onclick = "location.href = '../login/';">로그인 화면</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script>
    

        var loadedName = sessionStorage.getItem("username");
    
    
        var password = document.getElementById(".password1")
        var confirm_password = document.getElementById(".password2");
        
        function validatePassword(){
          if(password.value != confirm_password.value) {
            confirm_password.setCustomValidity("비밀번호가 맞지 않습니다.");
          } else {
            confirm_password.setCustomValidity(''); // 오류가 없으면 메시지를 빈 문자열로 설정해야한다. 오류 메시지가 비어 있지 않은 한 양식은 유효성 검사를 통과하지 않고 제출되지 않는다.
          }
        }
        
        password.onchange = validatePassword;
        confirm_password.onkeyup = validatePassword;
    
        
        </script>


{% endblock %}

</html>

webb/templates/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}

<div class="container" style="max-width:500px;">
	<form method="POST">
	  {% csrf_token %}
	  {% bootstrap_form boardForm %}
	  <input class="btn btn-dark rounded-pill col-12" type="submit" value="수정하기" onclick="location.href='/edit/{{board.pk}}/'">
  </form>
</div>

{% endblock %}